### ISSUE TITLE
[Feature Request] Settings not persistent when updated

### ISSUE THREAD

**Issue by nrgbistro** [darkalfx/requestrr#12]
I use an instance of Watchtower to automatically update all of my containers. When you pushed the most recent release, Watchtower updated my requestrr container and it refreshed everything. When I went to the web UI I got the create new user screen and none of the API keys or other settings were saved either, causing the bot to go offline. 

Would it be possible to make all of the settings/connections/users persist between container updates? Thanks!

**Comment by darkalfx** [comment]
Hey there, when using docker, you have to manually map the settings folder of Requestrr (/root/config) to a folder outside of the container, otherwise when the containers update you will lose all your settings as they were stored inside the container.

You have to add the -v parameter when creating the container, like this:

-v /user/home/darkalfx/requestrr:/root/config

**Comment by nrgbistro** [comment]
That fixed it. My bad, I assumed it stored config in `/config` and not `/root/config`.
