### ISSUE TITLE
Requestrr v1.0.12 docker update wipes settings?

### ISSUE THREAD

**Issue by edrock200** [darkalfx/requestrr#44]
Just curious if anyone else has run into this. Both a friend of mine and my docker setup last night auto updated requestrr to v1.0.12. after the update, settings were wiped. I restored v1.0.11 and it's settings, tried to update container to v1.0.12, same thing. Is this a bug, intended behavior or something unique about our setups? Thanks in advance.

**Comment by darkalfx** [comment]
Hey there, when using docker, you have to manually map the config folder of Requestrr (/root/config) to a folder outside of the container, otherwise when the containers update you will lose all your settings as they were stored inside the container.

You have to add the -v parameter when creating the container, like this:

-v /user/home/darkalfx/requestrr:/root/config

If you’ve done it and go into that folder, you should see two files: settings.json and notifications.json

**Comment by edrock200** [comment]
Thank you so much and sorry for wasting your time. I did have it mapped but when I went back to check, it looks like the yaml file somehow put an extra \ at the end of the path. Once I removed it, setting seem persistent again. Thank you!
